baseurl: "https://onspatial.github.io/GeoAnomalies24/"
title: "International Workshop on Spatial Computing for Geospatial Anomaly Detection @ACM SIGSPATIAL 2024"
canonifyurls: true
theme: "hugo-conference"
blackfriday:
    unsafe: true

GoogleAnalytics: ""

params:
  # Conference info
  Name: "GeoAnomalies@ ACM SIGSPATIAL 2024"
  Description: "International Workshop on Spatial Computing for Geospatial Anomaly Detection @ACM SIGSPATIAL 2024"
  Date: "October 29, 2024"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Georgia Tech Hotel and Conference Center"
  Address: "Georgia Tech Hotel and Conference Center"
  City:  "Atlanta, Georgia"
  State: "United States"
  Images: ["/img/logo.png"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer    
  #  - speakers
  #  - schedule    
    - location
    - cfp
    - deadline
  #  - contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    speakers: "Speakers"
    schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    contact: "Instructions for Authors"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now"
  #  link: ""

  intro:
    text: "The 1st ACM SIGSPATIAL International Workshop on Geospatial Anomaly Detection (GeoAnomalies’24) aims to bring together researchers and industry experts to discuss the latest advancements, challenges, and applications in the field of anomaly detection within spatial, geospatial, and spatiotemporal data. The workshop will foster collaboration and knowledge sharing among participants from a wide spectrum of research areas, including machine learning, time series analysis, statistics, remote sensing, geospatial analysis, and trajectory analysis, and therefore will provide a platform for a rich and diverse exchange of ideas."

  cfp:
    text: "The workshop seeks high-quality full (8-10 pages) and short (4 pages) papers that have not been published in other academic outlets and are not concurrently under peer review. Once accepted, at least one author is required to register for the workshop and the ACM SIGSPATIAL conference, as well as attend the workshop to present the accepted work which will then appear in the ACM Digital Library. As GeoAnomalies papers appear in the ACM SIGSPATIAL proceedings we follow the same submission process. Submission details can be found at https://easychair.org/my/conference?conf=geoanomalies24. Following the main-conference, we also allow full papers to have a two-page appendix beyond the ten pages limit."
    url: "https://onspatial.github.io/GeoAnomalies24/files/GeoAnomalies24.pdf"
    keywords: ["Theoretical Foundations of Geospatial Anomaly Detection", 
    "Machine Learning for Geospatial Anomaly Detection", 
    "Statistical Models for Geospatial Anomaly Detection", 
    "Complex Network Analysis", "Spatio-Temporal Modeling", 
    "Case Studies and Real-world Applications for Anomaly Detection on Spatial Data", 
    "Benchmarking and Evaluation"]

  organizer:
    general_chair: ["Yu-Ke Li, Tulane University","Carola Wenk, Tulane University","Andreas Züfle, Emory University"]
    pc_chair: [
    "Yao-Yi Chiang, University of Minnesota", "Enrico Mattei, Expedition Technology","Khurram Shafique, Novateur Research Solutions"
    ]
    pc_member: ["Leman Akoglu, Carnegie Mellon University",
    "Qunying Huang, University of Wisconsin Madison",
    "Joon-Seok Kim, Oak Ridge National Laboratory",
    "Peer Kröger, University of Kiel",
    "Andreas Lohrer, University of Kiel",
    "Erich Schubert, Technical University of Dortmund",
    "Cyrus Shahabi, University of Southern California",
    "Rose Yu, University of California"

    
    ]
    webchair: ["Yueyang Liu, Emory University"]

    
  deadline:
    submission: "August 16, 2024"
    notification: "September 14, 2024"
    camera: "October 4, 2024"
    workshopdate: "October 29, 2024"
    submissionsite: "https://easychair.org/my/conference?conf=geoanomalies24"
    studentgrant: "To be announced"

    
    
  #contact:
  
  speakers:
     - name: "Max Lau, Biostatistics, Rollins School of Public Health, Emory University"
       photo: "https://emoryeave.org/wp-content/uploads/MaxLau.jpeg"
       company: "Emory University"
       talk: 
         title: "ASSISTANT PROFESSOR, BIOSTATISTICS, Rollins School of Public Health"
    #     abstrct: ""
         bio: "Dr. Max Lau is Assistant Professor at Emory University, Rollins School of Public Health in the Biostatistics Department and is jointly appointed with the Epidemiology Department.  He earned his MPhil in Public Health and statistical modeling of infectious diseases at the University of Hongkong (2011).  He obtained his Ph.D. in statistical modeling of infectious diseases at Heriot-Watt University, Edinburgh (2015).  He completed his post doc work at Princeton University (2018) and began his career at Emory University in 2019.  He has developed new Bayesian methods and modelling techniques for disease data and data integration and designs and teaches graduate level machine learning and modeling classes."
         href: "https://emoryeave.org/bio/max-lau-phd/"

       
  schedule:
       - title: "Opening Remarks"
         time: "15:30-15:35"
         file: "Frontmatter.pdf"
       - title: "Keynote"
         authors: "Max Lau, , Biostatistics, Rollins School of Public Health, Emory University"
         bio: "Biostatistics, Rollins School of Public Health, Emory University"
         time: "15:35-16:30"
       - title: "Optimal Risk-aware POI Recommendations during Epidemics"
         authors: "Nina Yanin, Manos Papagelis"
         time: "16:30-16:50"
         file: "paper_1.pdf"
       - title: "EPIPOL: An Epidemiological Patterns of Life Simulation (Demonstration Paper)"
         authors: "Will Kohn, Hossein Amiri, Andreas Züfle"
         time: "16:50-17:10"
         file: "paper_2.pdf"
         
       - title: "Closing Remarks"
         time: "17:10-17:15"
         
            
# cover: https://pixabay.com/photos/buildings-city-night-street-lights-4829076/
